/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.conversordedivisas;


import java.awt.event.ItemEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Mewtwo
 */
public class Pantalla extends javax.swing.JFrame {

    int conversionA;
    int conversionDe;
    float conversion;
    float datoIngresado;
    float resultado;
    
    
    
    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
    }
    
    public static boolean validarNumeros(String datoIngresado){
        
        return datoIngresado.matches("[0.0000-9.0000000]{1,1000000}");
    }
    
    
    public String[]  getConversor(String tipo){
        {
            
            String[] tipoConver = new String[7];
            if(tipo.equalsIgnoreCase("Moneda")){
            
                    tipoConver[0] = "Seleccionar";
                    tipoConver[1] = "Peso Mexicano";
                    tipoConver[2] = "Dolar";
                    tipoConver[3] = "Euro";
                    tipoConver[4] = "Libras Esterlinas";
                    tipoConver[5] = "Yen Japones";
                    tipoConver[6] = "Won sur-coreano";
                    }
    
            if(tipo.equalsIgnoreCase("Distancia")){
            
                    tipoConver[0] = "Seleccionar";
                    tipoConver[1] = "Metro";
                    tipoConver[2] = "Centimetro";
                    tipoConver[3] = "Micrometro";
                    tipoConver[4] = "Milla";
                    tipoConver[5] = "Yarda";
                    tipoConver[6] = "Pie";
                    
        }
        return tipoConver;
        }
}
    // TODO add your handling code here:
    

    


    
    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        A = new javax.swing.JComboBox<>();
        BResultado = new javax.swing.JTextField();
        BIngresar = new javax.swing.JTextField();
        BttConv = new javax.swing.JButton();
        BLimpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ChooseConver = new javax.swing.JComboBox<>();
        De = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        A.setBackground(new java.awt.Color(255, 255, 255));
        A.setForeground(new java.awt.Color(0, 0, 0));
        A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AActionPerformed(evt);
            }
        });

        BResultado.setBackground(new java.awt.Color(255, 255, 255));
        BResultado.setForeground(new java.awt.Color(0, 0, 0));
        BResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BResultadoActionPerformed(evt);
            }
        });

        BIngresar.setBackground(new java.awt.Color(255, 255, 255));
        BIngresar.setForeground(new java.awt.Color(0, 0, 0));
        BIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BIngresarActionPerformed(evt);
            }
        });

        BttConv.setBackground(new java.awt.Color(255, 255, 255));
        BttConv.setForeground(new java.awt.Color(0, 0, 0));
        BttConv.setText("Convertir");
        BttConv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttConvActionPerformed(evt);
            }
        });

        BLimpiar.setBackground(new java.awt.Color(255, 255, 255));
        BLimpiar.setForeground(new java.awt.Color(0, 0, 0));
        BLimpiar.setText("Limpiar");
        BLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BLimpiarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Conversor");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Selecciona el tipo de conversion que le gustaria realizar:");

        ChooseConver.setBackground(new java.awt.Color(255, 255, 255));
        ChooseConver.setForeground(new java.awt.Color(0, 0, 0));
        ChooseConver.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Moneda", "Distancia" }));
        ChooseConver.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ChooseConverItemStateChanged(evt);
            }
        });
        ChooseConver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChooseConverActionPerformed(evt);
            }
        });

        De.setBackground(new java.awt.Color(255, 255, 255));
        De.setForeground(new java.awt.Color(0, 0, 0));
        De.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("De:");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("A:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(101, 101, 101))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(De, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BIngresar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BResultado))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BttConv, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(BLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ChooseConver, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ChooseConver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BttConv)
                    .addComponent(De, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BLimpiar))
                    .addComponent(BIngresar))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AActionPerformed

        conversionA = A.getSelectedIndex();
    }//GEN-LAST:event_AActionPerformed

    private void BResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BResultadoActionPerformed

    }//GEN-LAST:event_BResultadoActionPerformed

    private void BIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BIngresarActionPerformed

        datoIngresado = Float.parseFloat(BIngresar.getText());

    }//GEN-LAST:event_BIngresarActionPerformed

    private void BttConvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttConvActionPerformed

        Operaciones puente = new Operaciones();

        BIngresar.getText();

        if(!validarNumeros(BIngresar.getText().trim())){

            JOptionPane.showMessageDialog(null,"Ingrese un valor o revise que el valor ingresado sea un numero");

        }else{

            if(ChooseConver.getSelectedIndex() == 1){
                datoIngresado = Float.parseFloat(BIngresar.getText());
                conversionDe = De.getSelectedIndex();
                conversionA = A.getSelectedIndex();

                puente.setValor(datoIngresado);
                puente.setDivisaInicial(conversionDe);
                puente.setDivisaFinal(conversionA);
                float resultadoFinal = puente.convertir();

                BResultado.setText(Float.toString(resultadoFinal));
            }
            else if(ChooseConver.getSelectedIndex() == 2){
                datoIngresado = Float.parseFloat(BIngresar.getText());
                conversionDe = De.getSelectedIndex();
                conversionA = A.getSelectedIndex();

                puente.setValor(datoIngresado);
                puente.setDistanciaInicial(conversionDe);
                puente.setDistanciaFinal(conversionA);
                float resultadoFinal = puente.convertirDistancia();

                BResultado.setText(Float.toString(resultadoFinal));

            }
        }
    }//GEN-LAST:event_BttConvActionPerformed

    private void BLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BLimpiarActionPerformed
        this.BIngresar.setText("");
        this.BResultado.setText("");
        ChooseConver.setSelectedIndex(0);
        De.setSelectedIndex(0);
        A.setSelectedIndex(0);
    }//GEN-LAST:event_BLimpiarActionPerformed

    private void ChooseConverItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ChooseConverItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            if(this.ChooseConver.getSelectedIndex() > 0)
            {
                this.De.setModel(new DefaultComboBoxModel(this.getConversor(this.ChooseConver.getSelectedItem().toString())));

            }
            if(evt.getStateChange() == ItemEvent.SELECTED){
                if(this.ChooseConver.getSelectedIndex() > 0)
                {
                    this.A.setModel(new DefaultComboBoxModel(this.getConversor(this.ChooseConver.getSelectedItem().toString())));
                }
            }
        }
    }//GEN-LAST:event_ChooseConverItemStateChanged

    private void ChooseConverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChooseConverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChooseConverActionPerformed

    private void DeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeActionPerformed

    }//GEN-LAST:event_DeActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> A;
    private javax.swing.JTextField BIngresar;
    private javax.swing.JButton BLimpiar;
    private javax.swing.JTextField BResultado;
    private javax.swing.JButton BttConv;
    private javax.swing.JComboBox<String> ChooseConver;
    private javax.swing.JComboBox<String> De;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
